    # firebaseId: { type: String, index: true, unique: true },
    # email: { type: String, index: true },
    # joinType: { type: Number, default: 0 }, //0: 회원가입, 1:구글, 2: 카카오, 3: 페이스북, 4: 애플
    # secureLevel: { type: Number, default: 0 }, //0: 일반, 6: 관리자, 9: 모든 권한
    # gender: { type: Number, default: 0 }, //0: 남자, 1: 여자
    # extendInfo: {
    #   type: Schema.Types.ObjectId,
    #   ref: "UserExtendInfo",
    #   unique: true,
    # },
    # setting: { type: Schema.Types.ObjectId, ref: "Setting", default: null },
    # isDelete: { type: Boolean, default: false },
    # deletedAt: { type: Date },
    # createdAt: { type: Date, default: Date.now },

###
POST http://localhost:2394/api/v1/token/refresh
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2Y1NjEyN2IxNDc2MDVhM2Y1NWM3MDciLCJqb2luVHlwZSI6MCwiaWF0IjoxNjc3MDI1NjU2LCJleHAiOjE2NzcxMTIwNTZ9.rRNFYiAuvg-2VhjCqPF2hYEBPS1z9oPePeqNmxL4yBk
userId: 63f45c0109a9aa488b12c21a

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2Y1NjEyN2IxNDc2MDVhM2Y1NWM3MDciLCJqb2luVHlwZSI6MCwiaWF0IjoxNjc3MDI1NzgzLCJleHAiOjE5MzYyMjU3ODN9.ajLigUi1TwuC2sxZT8ne7iqEzFP0x7W7_PjizXqloXk"
}